# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Muhammad Ali Hassan
first_name: Muhammad
middle_name: Ali
last_name: Hassan
contact_note: 25100003@lums.edu.pk > `+92 333 6018187` > Lahore, Pakistan
description: > 
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
lang: en
icon: "👤" # Or provide an image in /assets/img/ if desired

url: https://AliHassanMirza1.github.io
baseurl:
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

  

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Analytics (if needed, leave blank otherwise)
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Comments (optional, can comment out if not needed)
# -----------------------------------------------------------------------------

giscus:
  repo:
  repo_id:
  category: Comments
  category_id:
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en

disqus_shortname: al-folio

# -----------------------------------------------------------------------------
# Removed Blog / Projects / News / Publications (commented out)
# -----------------------------------------------------------------------------
# (All blog settings, pagination, archives, scholar, etc. are removed or commented)

external_sources: []

# newsletter:
#   enabled: false

# announcements:
#   enabled: false

# latest_posts:
#   enabled: false

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor

keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jemoji
  - terser

# -----------------------------------------------------------------------------
# Sitemap settings
# -----------------------------------------------------------------------------
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------
jekyll-minifier:
  compress_javascript: false

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------
terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Image / WebP Settings
# -----------------------------------------------------------------------------
imagemagick:
  enabled: false
  widths: [480, 800, 1400]
  input_directories:
    - assets/img/
  input_formats: [".jpg", ".jpeg", ".png", ".tiff", ".gif"]
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------
enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: false
enable_medium_zoom: true
enable_progressbar: true
enable_video_embedding: false

# -----------------------------------------------------------------------------
# Third-party libraries
# -----------------------------------------------------------------------------
third_party_libraries:
  download: false
  # leaving the library versions is optional but harmless
  # (snipped out if you want further cleanup)

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------
# jekyll_get_json:
#   - data: resume
#     json: assets/json/resume.json

# jsonresume:
#   - basics
#   - work
#   - education
#   - publications
#   - projects
#   - volunteer
#   - awards
#   - certificates
#   - skills
#   - languages
#   - interests
#   - references

